@ECHO OFF
ECHO Clearing dist folter...
del /q dist\*
ECHO Minifying JS file...
uglifyjs -o dist\template.min.js js\template.js
ECHO Compiling CSS file...
scss --style compressed css\template.scss dist\template.min.css
ECHO Finished
